name: adviser
description: A Flutter app giving advices, build following clean architecture concepts.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  bloc_concurrency: ^0.2.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  http: ^1.0.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  mockito: ^5.4.2
  mocktail: ^0.3.0
  bloc_test: ^9.1.3
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
